runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /assignment-([0-9a-z]+)/.*
  script: assignment-\1.app

- url: (/|/index\.html|/.*)
  static_files: static/index.html
  upload: static/index.html